### ISSUE TITLE
Force usage of time offset in xs:dateTime fields

### ISSUE THREAD

**Issue by radboudp** [shapeshifter/shapeshifter-specification#48]
We should introduce a simple type that forces the usage of time offset (zone) for a date time

```
  <!-- -->
  <!-- DateTimeWithTimeZone Type -->
  <!-- -->
  <xs:simpleType name="DateTimeWithTimeZone">
    <xs:restriction base="xs:dateTime">
      <xs:pattern value=".*(Z|[+-][0-9]{2}:[0-9]{2})"/>
    </xs:restriction>
  </xs:simpleType>
```

**Comment by tomwetjens** [comment]
This could indeed have value as it is currently possible to e.g. send a ExpirationDateTime without offset making it ambiguous how the exact moment in time should be interpreted.

Additionally there were already incompatibilities between implementations because of different number of milliseconds digits in the datetime fields.
E.g. Java sends between 0 and 9 digits of milliseconds depending on which are zero. This can cause issues.

In the original proposed pattern above, the ".*" should be specified exactly:

```
  <!-- -->
  <!-- DateTimeType -->
  <!-- -->
  <xs:simpleType name="DateTimeType">
    <xs:restriction base="xs:dateTime">
      <xs:pattern value="^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2}):(\d{2}(?:\.\d*)?)(-(\d{2}):(\d{2})|Z)$"/>
    </xs:restriction>
  </xs:simpleType>
```
